const BASE = 'https://minecon.global/wp-content/uploads/2025';

export const ADS = [
  {
    id: 1,
    exhibitor_id: 'e07', exhibitor_name: 'SANY Group',
    label: 'Diamond Exhibitor',
    company: 'SANY Group',
    headline: 'World-Class Mining Equipment',
    sub: 'Visit Booth A07 · Main Hall',
    stat: '#1 Globally',
    tags: ['Excavators', 'Cranes', 'Pumps'],
    bg: 'from-orange-800 to-orange-950',
    accent: '#f97316',
    logo_url: `${BASE}/08/SANY.png`,
    url: 'https://www.sanyglobal.com',
    image_url: '/magazines/sany/concrete-pump.jpg',
    image_type: 'bg',
    image_pos: 'center 30%',
  },
  {
    id: 2,
    exhibitor_id: 'e13', exhibitor_name: 'Zimplow Holdings',
    label: 'Diamond Exhibitor',
    company: 'Zimplow Holdings',
    headline: 'Feed, Connect, Power & Build',
    sub: 'Visit Booth A13 · Main Hall',
    stat: 'Est. 1949',
    tags: ['Agriculture', 'Mining', 'Power'],
    bg: 'from-slate-800 to-slate-950',
    accent: '#22c55e',
    logo_url: `${BASE}/08/ZINMPLOW.png`,
    url: 'https://zimplow.co.zw/',
    image_url: '/banners/zimplow-jcb.png',
    image_type: 'cutout',
  },
  {
    id: 3,
    exhibitor_id: 'e02', exhibitor_name: 'Isuzu Zimbabwe',
    label: 'Diamond Exhibitor',
    company: 'Isuzu Zimbabwe',
    headline: 'Built for the Toughest Conditions',
    sub: 'Visit Booth A02 · Main Hall',
    stat: 'Since 1916',
    tags: ['D-MAX', 'Trucks', 'Commercial'],
    bg: 'from-blue-900 to-slate-950',
    accent: '#60a5fa',
    logo_url: `${BASE}/08/ISUZU.png`,
    url: 'https://www.autoworld.co.zw/',
    image_url: '/banners/isuzu-dmax.jpg',
    image_type: 'bg',
    image_pos: 'center 55%',
  },
  {
    id: 4,
    exhibitor_id: null, exhibitor_name: null,
    label: 'Register Now',
    company: 'MineCon 2026',
    headline: 'Free Visitor Registration Open',
    sub: 'October 2026 · Artfarm Grounds, Harare',
    stat: 'Free Entry',
    tags: ['Mining', 'Construction', 'Innovation'],
    bg: 'from-amber-700 to-amber-900',
    accent: '#ffffff',
    logo_url: `${BASE}/07/MINECON-VECTOR-LOGO.png`,
    url: '/register',
    internal: true,
  },
  {
    id: 5,
    exhibitor_id: 'e16', exhibitor_name: 'LiuGong Zimbabwe',
    label: 'Diamond Exhibitor',
    company: 'LiuGong Zimbabwe',
    headline: 'Tough World. Tough Equipment.',
    sub: 'Visit Booth A16 · Main Hall',
    stat: '50+ Years',
    tags: ['Loaders', 'Excavators', 'Dozers'],
    bg: 'from-blue-900 to-emerald-950',
    accent: '#6ee7b7',
    logo_url: `${BASE}/09/LIUGONG.png`,
    url: 'https://www.liugong.com/en/product/?type_id=200',
    image_url: '/banners/liugong-equipment.jpg',
    image_type: 'bg',
    image_pos: 'right center',
  },
  {
    id: 6,
    exhibitor_id: 'e01', exhibitor_name: 'Steel Warehouse Holdings',
    label: 'Diamond Exhibitor',
    company: 'Steel Warehouse',
    headline: "Zimbabwe's Leading Steel Merchant",
    sub: 'Visit Booth A01 · Main Hall',
    stat: '800+ Products',
    tags: ['Structural', 'Roofing', 'Tubing'],
    bg: 'from-zinc-800 to-zinc-950',
    accent: '#f97316',
    logo_url: `${BASE}/08/STEEL-WAREHOUSE.png`,
    url: 'https://swh.co.zw/',
    image_url: '/banners/swh-steel.jpg',
    image_type: 'bg',
    image_pos: 'center 20%',
  },
];