const BASE = 'https://minecon.global/wp-content/uploads/2025';

export const ADS = [
  {
    id: 1,
    exhibitor_id: 'e07', exhibitor_name: 'SANY Group',
    label: 'Diamond Exhibitor',
    company: 'SANY Group',
    headline: 'World-Class Mining Equipment',
    sub: 'Visit Booth A07 · Main Hall',
    bg: 'from-orange-700 to-orange-900',
    accent: '#f59e0b',
    logo_url: `${BASE}/08/SANY.png`,
    url: 'https://www.sanyglobal.com',
  },
  {
    id: 2,
    exhibitor_id: 'e13', exhibitor_name: 'Zimplow Holdings',
    label: 'Diamond Exhibitor',
    company: 'Zimplow Holdings',
    headline: 'Industrial Solutions for Africa',
    sub: 'Visit Booth A13 · Main Hall',
    bg: 'from-slate-700 to-slate-900',
    accent: '#f59e0b',
    logo_url: `${BASE}/08/ZINMPLOW.png`,
    url: 'http://www.zimplow.co.zw',
  },
  {
    id: 3,
    exhibitor_id: 'e02', exhibitor_name: 'Isuzu Zimbabwe',
    label: 'Diamond Exhibitor',
    company: 'Isuzu Zimbabwe',
    headline: 'Built for the Toughest Conditions',
    sub: 'Visit Booth A02 · Main Hall',
    bg: 'from-blue-800 to-blue-900',
    accent: '#60a5fa',
    logo_url: `${BASE}/08/ISUZU.png`,
    url: 'https://www.isuzu.co.zw',
  },
  {
    id: 4,
    exhibitor_id: null, exhibitor_name: null,
    label: 'Register Now',
    company: 'MineCon 2026',
    headline: 'Free Visitor Registration Open',
    sub: 'Dates TBC · Artfarm Grounds, Harare',
    bg: 'from-amber-700 to-amber-900',
    accent: '#ffffff',
    logo_url: `${BASE}/07/MINECON-VECTOR-LOGO.png`,
    url: '/register',
    internal: true,
  },
  {
    id: 5,
    exhibitor_id: 'e16', exhibitor_name: 'LiuGong Zimbabwe',
    label: 'Diamond Exhibitor',
    company: 'LiuGong Zimbabwe',
    headline: 'Heavy Equipment for Every Job',
    sub: 'Visit Booth A16 · Main Hall',
    bg: 'from-emerald-800 to-emerald-900',
    accent: '#6ee7b7',
    logo_url: `${BASE}/09/LIUGONG.png`,
    url: 'https://liugong.com',
  },
  {
    id: 6,
    exhibitor_id: 'e01', exhibitor_name: 'Steel Warehouse Holdings',
    label: 'Diamond Exhibitor',
    company: 'Steel Warehouse Holdings',
    headline: 'Steel & Metal Solutions',
    sub: 'Visit Booth A01 · Main Hall',
    bg: 'from-zinc-700 to-zinc-900',
    accent: '#f59e0b',
    logo_url: `${BASE}/08/STEEL-WAREHOUSE.png`,
    url: 'http://www.swh.co.zw',
  },
];
